"""
Pydantic schemas for API requests and responses.

Simplified structure:
- RFPResponse has ONE document_code field
- The LLM writes complete python-docx code with seaborn charts and mermaid diagrams inline
"""

from typing import Optional
from pydantic import BaseModel, Field


# ============ RFP Response Model ============

class RFPResponse(BaseModel):
    """
    Complete RFP response.
    
    The document_code field contains Python code that creates the full Word document.
    The code can use python-docx, seaborn/matplotlib for charts, and mermaid CLI for diagrams.
    """
    document_code: str = Field(
        ..., 
        description="Python code that creates the complete proposal Word document."
    )


# ============ Planner Models ============

class PlannedSection(BaseModel):
    """A planned section of the proposal."""
    title: str = Field(..., description="Section title")
    summary: str = Field(..., description="High-level summary of what this section should cover")
    related_requirements: list[str] = Field(default_factory=list, description="Requirement IDs this section addresses")
    rfp_pages: list[int] = Field(default_factory=list, description="RFP page numbers (integers only)")
    suggested_diagrams: list[str] = Field(default_factory=list, description="Suggested mermaid diagram types")
    suggested_charts: list[str] = Field(default_factory=list, description="Suggested seaborn chart types")
    suggested_tables: list[str] = Field(default_factory=list, description="Suggested table types")


class ProposalPlan(BaseModel):
    """Complete proposal plan generated by the planner."""
    overview: str = Field(..., description="High-level overview of the proposal strategy")
    sections: list[PlannedSection] = Field(default_factory=list)
    key_themes: list[str] = Field(default_factory=list, description="Key themes to emphasize throughout")
    win_strategy: str = Field(default="", description="Strategy for winning this RFP")


# ============ Critiquer Models ============

class CritiqueResult(BaseModel):
    """Result from the critiquer agent."""
    needs_revision: bool = Field(..., description="Whether the document needs revisions")
    critique: str = Field(default="", description="Detailed critique if revisions needed")
    strengths: list[str] = Field(default_factory=list, description="What the document does well")
    weaknesses: list[str] = Field(default_factory=list, description="Areas that need improvement")
    priority_fixes: list[str] = Field(default_factory=list, description="Priority fixes if needs_revision is True")


# ============ RFP Analysis Models ============

class RFPRequirement(BaseModel):
    """A requirement extracted from an RFP."""
    id: str = Field(..., description="Unique ID like REQ-001")
    description: str = Field(..., description="Requirement description")
    category: str = Field(
        ..., 
        pattern="^(technical|management|cost|experience|compliance|other)$"
    )
    is_mandatory: bool = Field(..., description="Whether mandatory")
    priority: Optional[str] = Field(
        None, 
        pattern="^(high|medium|low)$"
    )


class EvaluationCriterion(BaseModel):
    """An evaluation criterion from the RFP."""
    criterion: str
    weight: Optional[float] = None
    description: Optional[str] = None


class SubmissionRequirements(BaseModel):
    """Submission logistics from the RFP."""
    deadline: Optional[str] = None
    format: Optional[str] = None
    page_limit: Optional[int] = None
    sections_required: Optional[list[str]] = None


class RFPAnalysis(BaseModel):
    """Complete analysis of an RFP document."""
    summary: str = Field(..., description="Brief summary of the RFP")
    requirements: list[RFPRequirement]
    evaluation_criteria: Optional[list[EvaluationCriterion]] = None
    submission_requirements: Optional[SubmissionRequirements] = None
    key_differentiators: Optional[list[str]] = None


# ============ API Request/Response Models ============

class GenerateRFPRequest(BaseModel):
    """Request body for RFP generation (used with form data)."""
    pass


class GenerateRFPResponse(BaseModel):
    """Response from RFP generation endpoint."""
    success: bool
    message: str
    rfp_response: Optional[RFPResponse] = None
    analysis: Optional[RFPAnalysis] = None
    docx_download_url: Optional[str] = None
    processing_time_seconds: Optional[float] = None


class GeneratedCodeSnippet(BaseModel):
    """Single generated code snippet extracted from document_code."""
    snippet_id: str
    title: str
    code: str
    asset_filename: Optional[str] = None
    asset_base64: Optional[str] = None
    asset_content_type: Optional[str] = None
    html_code: Optional[str] = None


class GeneratedCodePackage(BaseModel):
    """Grouped code snippets for easier manual editing."""
    mermaid: list[GeneratedCodeSnippet] = Field(default_factory=list)
    tables: list[GeneratedCodeSnippet] = Field(default_factory=list)
    diagrams: list[GeneratedCodeSnippet] = Field(default_factory=list)


class ExtractReqsResponse(BaseModel):
    """Response from requirement extraction endpoint."""
    success: bool
    message: str
    analysis: Optional[RFPAnalysis] = None
    run_id: Optional[str] = None


class PlanStepRequest(BaseModel):
    """Request body for planning endpoint."""
    analysis: RFPAnalysis
    company_context_text: Optional[str] = None
    comment: Optional[str] = None
    previous_plan: Optional[ProposalPlan] = None
    run_id: Optional[str] = None


class PlanStepResponse(BaseModel):
    """Response from planning endpoint."""
    success: bool
    message: str
    plan: Optional[ProposalPlan] = None
    run_id: Optional[str] = None


class CritiqueStepRequest(BaseModel):
    """Request body for critique endpoint."""
    analysis: RFPAnalysis
    document_code: str
    comment: Optional[str] = None
    run_id: Optional[str] = None


class CritiqueStepResponse(BaseModel):
    """Response from critique endpoint."""
    success: bool
    message: str
    critique: Optional[CritiqueResult] = None
    run_id: Optional[str] = None


class GenerateRFPStepResponse(BaseModel):
    """Response from custom generate-rfp endpoint."""
    success: bool
    message: str
    document_code: str
    docx_base64: str
    docx_filename: str
    docx_content_type: str = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    execution_stats: dict = Field(default_factory=dict)
    code_package: GeneratedCodePackage = Field(default_factory=GeneratedCodePackage)
    run_id: Optional[str] = None
    docx_download_url: Optional[str] = None


class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    version: str
    llm_configured: bool
    auth_enabled: bool
    images_enabled: bool


class WorkflowStepConfig(BaseModel):
    """Configuration for a single workflow step."""
    id: str
    name: str
    description: str
    enabled: bool = True


class ConfigResponse(BaseModel):
    """Public configuration response."""
    auth_enabled: bool
    images_enabled: bool
    enable_planner: bool = False
    enable_critiquer: bool = False
    workflow_steps: list[WorkflowStepConfig] = []
    msal_client_id: Optional[str] = None
    msal_tenant_id: Optional[str] = None
    msal_redirect_uri: Optional[str] = None
    msal_scopes: Optional[list[str]] = None


class PromptDefinition(BaseModel):
    """Single prompt definition."""
    name: str
    content: str


class PromptsResponse(BaseModel):
    """Read-only prompt catalog for frontend display."""
    system_prompts: list[PromptDefinition] = Field(default_factory=list)
    base_prompts: list[PromptDefinition] = Field(default_factory=list)
