"""
Prompts module - Contains all LLM prompts for the RFP Builder workflow.
"""

from .system_prompts import (
    RFP_ANALYZER_SYSTEM_PROMPT,
    RFP_SECTION_GENERATOR_SYSTEM_PROMPT,
    RFP_REVIEWER_SYSTEM_PROMPT,
    RFP_FINALIZER_SYSTEM_PROMPT,
)

__all__ = [
    "RFP_ANALYZER_SYSTEM_PROMPT",
    "RFP_SECTION_GENERATOR_SYSTEM_PROMPT",
    "RFP_REVIEWER_SYSTEM_PROMPT",
    "RFP_FINALIZER_SYSTEM_PROMPT",
]
